### ISSUE TITLE
Portugueses Translations

### ISSUE THREAD

**Issue by SteveOriginal** [FossilsArcheologyRevival/FossilArcheology1.7#100]
The Portuguese Translations Are Horribles!Need Much Changes Principally Eggs And items,Tell Me On Skype(Lucas_Lima_14) And Give Me A Document Copy Of The Translations pt_BR And pt_PT.

**Comment by 4f6f3b** [comment]
Hey SteveOriginal, drop an email to fossils.revival@gmail.com and we can get it ready for you. :)

**Comment by SteveOriginal** [comment]
Thanks! I Sended It,My Email Is lucasbarbosadelima@outlook.com

**Comment by 4f6f3b** [comment]
Sent you an email. :)
