### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ssherlockhemlock** [FossilsArcheologyRevival/FossilArcheology1.7#102]
The mod crashes immediatly  both on its own and with other mods. The crash report says something about magnolia flower block but when that file was removed nothing changed. Mac OS, everything updated plenty of ram. Discovered when using technic launcher. Past version worked fine. Works fine it FTB launcher.

**Comment by 4f6f3b** [comment]
What mod version? Can I get a pastebin of the log file?

**Comment by Ssherlockhemlock** [comment]
The latest version 7.1, also sorry it don't know what you mean by pastebin of the log file, I'm terrible at computer stuff, Ill post the crash report if thats what you meant if not please tell me where to find what you mean sorry and thanks,
--- Minecraft Crash Report ----
// Daisy, daisy...

Time: 13/04/15 20:25
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/fossil/blocks/BlockMagnoliaFlower
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:156)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:521)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
	at MinecraftLoader.ClientHelper.startGame(ClientHelper.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.NoClassDefFoundError: mods/fossil/blocks/BlockMagnoliaFlower
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:462)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at MinecraftLoader.MinecraftDummyContainer.callMethod(MinecraftDummyContainer.java:118)
	at MinecraftLoader.MinecraftDummyContainer.onModEvent(MinecraftDummyContainer.java:110)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
	... 11 more
Caused by: java.lang.ClassNotFoundException: mods.fossil.blocks.BlockMagnoliaFlower
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 40 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockBush
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
	... 42 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockBush
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:97)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 47 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 108004624 bytes (103 MB) / 280600576 bytes (267 MB) up to 2138767360 bytes (2039 MB)
	JVM Flags: 2 total; -Xmx2048m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 169 mods loaded, 169 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{6.4.49.965} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed
	Forge{9.11.1.965} [Minecraft Forge] (modpack.jar) Unloaded->Constructed
	BetterSprinting{v11} [Better Sprinting (core)] (minecraft.jar) Unloaded->Constructed
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
	minecraftloader{0.1} [MinecraftLoader] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.6.1.9} [Not Enough Items] (NotEnoughItems 1.6.1.9.jar) Unloaded->Constructed
	TConstruct-Preloader{0.0.1} [Tinkers Corestruct] (minecraft.jar) Unloaded->Constructed
	AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed
	denLib{3.2.6} [denLib] (minecraft.jar) Unloaded->Constructed
	PowerCrystalsCore{1.1.8} [PowerCrystals Core] (powercrystalscore-1.1.8-9.jar) Unloaded->Constructed
	switches|pistontweak{1.3.0 build 25} [Switches|PistonTweak] (minecraft.jar) Unloaded->Constructed
	OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed
	DenEvents{1.0} [DenEvents] (DenEvents.jar) Unloaded->Constructed
	mod_MouseTweaks{2.3.4 (for Minecraft 1.6.4)} [Mouse Tweaks] ([1.6.4] Mouse Tweaks 2.3.4.zip) Unloaded->Constructed
	bspkrsCore{v5.3(1.6.4)} [bspkrsCore] ([1.6.4]bspkrsCorev5.3.zip) Unloaded->Constructed
	TreeCapitator{Forge 1.6.4.r09} [Treecapitator] ([1.6.4]TreeCapitator.Forge.1.6.4.r09.Universal.zip) Unloaded->Constructed
	Agriculture{1.0.0} [Agriculture] (Agriculture-1.6.4-1.2.13.jar) Unloaded->Constructed
	arsmagica2{1.1.2b} [Ars Magica 2] (AM2_1.1.2b.zip) Unloaded->Constructed
	AnimationAPI{1.1.1} [AnimationAPI] (AnimationAPI v1.1.2 mc1.6.4.zip) Unloaded->Constructed
	AppliedEnergistics{rv14.finale3} [Applied Energistics] (applied-energistics-rv14-finale3.jar) Unloaded->Constructed
	ArchimedesShipsMod{1.6.2 v1.4.4} [Archimedes' Ships] (archimedes-ships-1.4.5.zip) Unloaded->Constructed
	BiblioCraft{1.5.5} [BiblioCraft] (BiblioCraft[v1.5.5].zip) Unloaded->Constructed
	Natura{2.1.14} [Natura] (natura-2.1.14.jar) Unloaded->Constructed
	BiomesOPlenty{1.2.1} [Biomes O' Plenty] (BiomesOPlenty-universal-1.6.4-1.2.1.434.jar) Unloaded->Constructed
	BiblioWoodsBoP{1.3} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.3].zip) Unloaded->Constructed
	CoFHCore{2.0.0.5} [CoFH Core] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed
	NetherOres{1.6.2R2.2.2} [Nether Ores] (NetherOres-2.2.2-55.jar) Unloaded->Constructed
	BuildCraft|Core{4.2.2} [BuildCraft] (buildcraft-A-4.2.2.jar) Unloaded->Constructed
	UniversalElectricity{3.1.0} [Universal Electricity] (Universal-Electricity-3.1.0.114-core.jar) Unloaded->Constructed
	ForgeMultipart{1.0.0.244} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed
	ThermalExpansion{3.0.0.5} [Thermal Expansion] (ThermalExpansion-3.0.0.5.jar) Unloaded->Constructed
	IC2{2.0.397-experimental} [IndustrialCraft 2] (industrialcraft-2_2.0.397-experimental.jar) Unloaded->Constructed
	BuildCraft|Builders{4.2.2} [BC Builders] (buildcraft-A-4.2.2.jar) Unloaded->Constructed
	BuildCraft|Energy{4.2.2} [BC Energy] (buildcraft-A-4.2.2.jar) Unloaded->Constructed
	BuildCraft|Factory{4.2.2} [BC Factory] (buildcraft-A-4.2.2.jar) Unloaded->Constructed
	BuildCraft|Transport{4.2.2} [BC Transport] (buildcraft-A-4.2.2.jar) Unloaded->Constructed
	MineFactoryReloaded{1.6.4R2.7.9} [MineFactory Reloaded] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForestryPre{1.6.4R2.7.9} [MFR Compat: Forestry (part 2)] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	Forestry{2.3.1.1} [Forestry for Minecraft] (forestry-A-2.3.1.1.jar) Unloaded->Constructed
	BiblioWoodsForestry{1.3} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.3].zip) Unloaded->Constructed
	BiblioWoodsNatura{1.1} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.1].zip) Unloaded->Constructed
	ComputerCraft{1.63} [ComputerCraft] (ComputerCraft1.63.jar) Unloaded->Constructed
	Mekanism{6.0.5} [Mekanism] (Mekanism-6.0.5.46.jar) Unloaded->Constructed
	BigReactors{0.3.4A2} [Big Reactors] (BigReactors-0.3.4A2.jar) Unloaded->Constructed
	Billund{1.01} [BILLUND] (BILLUND1.01.zip) Unloaded->Constructed
	BinnieCore{1.8.0} [Binnie Core] (binnie-mods-1.8.0.jar) Unloaded->Constructed
	ExtraBees{1.8.0} [Extra Bees] (binnie-mods-1.8.0.jar) Unloaded->Constructed
	ExtraTrees{1.8.0} [Extra Trees] (binnie-mods-1.8.0.jar) Unloaded->Constructed
	BuildCraft|Silicon{4.2.2} [BC Silicon] (buildcraft-A-4.2.2.jar) Unloaded->Constructed
	ChargePads{3.0.0} [Charge Pads] (chargepads-1.6.2-universal-3.0.0.94-experimental.jar) Unloaded->Constructed
	mod_ChatBubbles{3.1.4.4.0} [MamiyaOtaru's Chat Bubbles] (ChatBubbles1.6.4.zip) Unloaded->Constructed
	ChickenChunks{1.3.3.4} [ChickenChunks] (ChickenChunks 1.3.3.4.jar) Unloaded->Constructed
	CoFHLoot{2.0.0.5} [CoFH Loot] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed
	CoFHMasquerade{2.0.0.5} [CoFH Masquerade] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed
	CoFHSocial{2.0.0.5} [CoFH Social] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed
	CoFHWorld{2.0.0.5} [CoFH World] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed
	CompactSolars{4.4.20.305} [Compact Solar Arrays] (compactsolars-universal-1.6.4-4.4.20.305.zip) Unloaded->Constructed
	ConfigMod{v1.0} [Extended Mod Config] (ConfigMod for MC v1.6.4.zip) Unloaded->Constructed
	CoroAI{v1.0} [CoroAI] (CoroUtil for MC v1.6.4.zip) Unloaded->Constructed
	DamageIndicatorsMod{2.9.2.3} [Damage Indicators] (damage-indicators-2.9.2.3.zip) Unloaded->Constructed
	DragonMounts{r36} [Dragon Mounts] (dragonmount_r36_mc1.6.x.zip) Unloaded->Constructed
	EnderStorage{1.4.3.6} [EnderStorage] (EnderStorage 1.4.3.6.jar) Unloaded->Constructed
	EE3{0.1} [Equivalent Exchange 3] (EquivalentExchange3-1.6.4-0.1.142.jar) Unloaded->Constructed
	LomLib{1.2.0} [LomLib] (LomLib-universal-1.2.0.jar) Unloaded->Constructed
	Equivalency{1.6.4} [Equivalency] (Equivalency-universal-1.6.4.jar) Unloaded->Constructed
	ExtendedRenderer{v1.0} [Extended Renderer] (ExtendedRenderer for MC v1.6.4.zip) Unloaded->Constructed
	Waila{1.5.2a} [Waila] (Waila_1.5.2a.zip) Unloaded->Constructed
	extracells{1.6.8f} [ExtraCells] (ExtraCells-1.6.8f.jar) Unloaded->Constructed
	ExtraUtilities{1.0.3c} [Extra Utilities] (extrautils-1.0.3c.zip) Unloaded->Constructed
	factorization{0.8.34} [Factorization] (Factorization-0.8.34.jar) Unloaded->Constructed
	factorization.misc{0.8.34} [Factorization Miscellaneous Nonsense] (Factorization-0.8.34.jar) Unloaded->Constructed
	factorization.notify{0.8.34} [Factorization Notification System] (Factorization-0.8.34.jar) Unloaded->Constructed
	factorization.dimensionalSlice{0.8.34} [Factorization Dimensional Slices] (Factorization-0.8.34.jar) Unloaded->Constructed
	DeathCounter{2.0.0} [DeathCounter] (files^DeathCounter2.0.0.zip) Unloaded->Constructed
	FlansMod{4.1.1} [Flans Mod] (FlansMod-4.1.1.jar) Unloaded->Constructed
	flatsigns{1.4.0} [Flat Signs] (flatsigns-1.6.2-universal-1.4.0.15.jar) Unloaded->Constructed
	fossil{1.7.10 Build 7.1.0} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.1.jar) Unloaded
	GalacticraftCore{2.0.14} [Galacticraft Core] (Galacticraft-1.6.4-2.0.14.1084.jar) Unloaded->Constructed
	GalacticraftMars{2.0.14} [Galacticraft Mars] (Galacticraft-Planets-1.6.4-2.0.14.1084.jar) Unloaded->Constructed
	iChunUtil{2.4.0} [iChunUtil] (util^iChunUtil2.4.0.zip) Unloaded->Constructed
	GraviGun{2.0.0} [GraviGun] (gravity-gun-2.0.0.zip) Unloaded->Constructed
	Hats{2.1.8} [Hats] (Hats2.1.8.zip) Unloaded->Constructed
	HatStand{2.1.0} [HatStand] (HatStand2.1.0.zip) Unloaded->Constructed
	InfernalMobs{1.4.4} [Infernal Mobs] (InfernalMobs_1.6.4.zip) Unloaded->Constructed
	inventorytweaks{1.56} [Inventory Tweaks] (inventory-tweaks-1.6.2-1.56-b77.jar) Unloaded->Constructed
	IronChest{5.4.1.614} [Iron Chest] (iron-chests-1.6.4.zip) Unloaded->Constructed
	Thaumcraft{4.1.0g} [Thaumcraft] (Thaumcraft4.1.0g.zip) Unloaded->Constructed
	Railcraft{8.4.0.0} [Railcraft] (Railcraft_1.6.4-8.4.0.0.jar) Unloaded->Constructed
	TConstruct{1.6.X_1.5.5.7} [Tinkers' Construct] (TConstruct_mc1.6.4_1.5.5.7.jar) Unloaded->Constructed
	ThaumicTinkerer{2.3-140} [Thaumic Tinkerer] (ThaumicTinkerer-2.3-140.jar) Unloaded->Constructed
	MagicBees{2.1.12} [Magic Bees] (magicbees-2.1.12.jar) Unloaded->Constructed
	MekanismGenerators{6.0.5} [MekanismGenerators] (MekanismGenerators-6.0.5.46.jar) Unloaded->Constructed
	MekanismTools{6.0.5} [MekanismTools] (MekanismTools-6.0.5.46.jar) Unloaded->Constructed
	MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAppliedEnergistics{1.6.4R2.7.9} [MFR Compat: Applied Energistics] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAtum{1.6.4R2.7.9} [MFR Compat: Atum] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBackTools{1.6.4R2.7.9} [MFR Compat: BackTools] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBuildCraft{1.6.4R2.7.9} [MFR Compat: BuildCraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatChococraft{1.6.4R2.7.9} [MFR Compat: Chococraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatExtraBiomes{1.6.4R2.7.9} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForestry{1.6.4R2.7.9} [MFR Compat: Forestry] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForgeMicroblock{1.6.4R2.7.9} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatIC2{1.6.4R2.7.9} [MFR Compat: IC2] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	Mystcraft{0.10.12.01} [Mystcraft] (mystcraft-uni-1.6.4-0.10.12.01.zip) Unloaded->Constructed
	MineFactoryReloaded|CompatMystcraft{1.6.4R2.7.9} [MFR Compat: Mystcraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatPams{1.6.4R2.7.9} [MFR Compat: Pam's Mods] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	ProjRed|Core{4.3.5.30} [ProjectRed] (ProjectRedBase-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	ProjRed|Exploration{4.3.5.30} [ProjectRed-Exploration] (ProjectRedWorld-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatProjRed{1.6.4R2.7.9} [MFR Compat ProjectRed] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatRailcraft{1.6.4R2.7.9} [MFR Compat: Railcraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatRP2{1.6.4R2.7.9} [MFR Compat: RP2] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatSufficientBiomes{1.6.4R2.7.9} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThaumcraft{1.6.4R2.7.9} [MFR Compat: Thaumcraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThermalExpansion{1.6.4R2.7.9} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	TwilightForest{1.20.5} [The Twilight Forest] (twilightforest-1.6.4-1.20.5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatTwilightForest{1.6.4R2.7.9} [MFR Compat: TwilightForest] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatVanilla{1.6.4R2.7.9} [MFR Compat: Vanilla] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatXyCraft{1.6.4R2.7.9} [MFR Compat: XyCraft] (MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
	BuildMod{v1.0} [Build Mod] (ModBuild for MC v1.6.4.zip) Unloaded->Constructed
	ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [ResonantEngine] (Resonant-Engine-1.2.0.349-universal.jar) Unloaded->Constructed
	MFFS{3.6.3} [Modular Force Field System] (Modular-Force-Field-System-3.6.3.91-core.jar) Unloaded->Constructed
	numina{0.1.2-55} [Numina] (Numina-1.6.2-0.1.2-55.jar) Unloaded->Constructed
	powersuits{0.10.0-91} [MachineMuse's Modular Powersuits] (modular-powersuits-1.6.4-0.10.0-91.jar) Unloaded->Constructed
	Morph{0.7.1} [Morph] (Morph-Beta-0.7.1.zip) Unloaded->Constructed
	NEIPlugins{1.1.0.6} [NEI Plugins] (nei-plugins-1.1.0.6.jar) Unloaded->Constructed
	NEIAddons{1.10.4.64} [NEI Addons] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
	NEIAddons|AE{1.10.4.64} [NEI Addons: Applied Energistics] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
	NEIAddons|MiscPeripherals{1.10.4.64} [NEI Addons: Misc Peripherals] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
	NEIAddons|ExtraBees{1.10.4.64} [NEI Addons: Extra Bees] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
	NEIAddons|Forestry{1.10.4.64} [NEI Addons: Forestry] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
	NEIAddons|CraftingTables{1.10.4.64} [NEI Addons: Crafting Tables] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed
	NotEnoughCodecs{0.1} [NotEnoughCodecs] (NotEnoughCodecs-0.1.jar) Unloaded->Constructed
	ObsidiPlates{2.0.0} [Obsidian Pressure Plates] (obsidiplates-2.0.0.15.jar) Unloaded->Constructed
	OpenMods{0.5} [OpenMods] (OpenModsLib-0.5.jar) Unloaded->Constructed
	OpenBlocks{1.2.8} [OpenBlocks] (OpenBlocks-1.2.8.jar) Unloaded->Constructed
	OreSpawn{164.18} [OreSpawn] (orespawn164v18.zip) Unloaded->Constructed
	PortalGun{2.0.2} [PortalGun] (PortalGun2.0.2.zip) Unloaded->Constructed
	powersuitaddons{@VERSION@} [Andrew's Modular Powersuits Addons] (powersuitaddons-1.6.4-884.jar) Unloaded->Constructed
	ProjRed|Transportation{4.3.5.30} [ProjectRed-Transportation] (ProjectRedMechanical-BETA-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	ProjRed|Compatibility{4.3.5.30} [ProjectRed-Compatibility] (ProjectRedCompat-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	ProjRed|Integration{4.3.5.30} [ProjectRed-Integration] (ProjectRedIntegration-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	ProjRed|Transmission{4.3.5.30} [ProjectRed-Transmission] (ProjectRedIntegration-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	ProjRed|Illumination{4.3.5.30} [ProjectRed-Illumination] (ProjectRedLighting-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	ProjRed|Expansion{4.3.5.30} [ProjectRed-Expansion] (ProjectRedMechanical-BETA-1.6.4-4.3.5.30.jar) Unloaded->Constructed
	QuarryPlus{1.0.0} [QuarryPlus] (QuarryPlus-1.6.4-1.0.3.jar) Unloaded->Constructed
	Redstone Arsenal{1.0.0.0} [Redstone Arsenal] (RedstoneArsenal-1.0.0.0.jar) Unloaded->Constructed
	JAKJ_RedstoneInMotion{2.3.0.0} [Redstone In Motion] (RedstoneInMotion_2.3.0.0_mc1.6.zip) Unloaded->Constructed
	Shatter{2.0.2} [Shatter] (Shatter2.0.2.zip) Unloaded->Constructed
	SS2{2 (build 2)} [Soul Shards 2] (SoulShards-2.0.15-universal-srg.jar) Unloaded->Constructed
	SparklezBlock{1.0.0 Alpha} [Sparklez Block] (SparklezBlockBeta+MultiplayerSupport.zip) Unloaded->Constructed
	StevesCarts{2.0.0.b10} [Steve's Carts 2] (StevesCarts2.0.0.b10.zip) Unloaded->Constructed
	Streak{2.1.0} [Streak] (Streak2.1.0.zip) Unloaded->Constructed
	switches{1.3.0} [Switches] (switches-1.6.4-universal-coremod-1.3.0.25.jar) Unloaded->Constructed
	Sync{2.2.2} [Sync] (Sync2.2.2.zip) Unloaded->Constructed
	telepads{1.6.4 v5} [Teleportation Pads] (TelePads 1.6.4 v5.zip) Unloaded->Constructed
	TiCTooltips{1.1.6} [TiC Tooltips] (TiCTooltips-mc1.6.4-1.1.6.jar) Unloaded->Constructed
	tradeboothmod{0.6.4.2} [Trade Booth Mod] (tradebooth.0.6.4.2.zip) Unloaded->Constructed
	Translocator{1.1.0.15} [Translocator] (Translocator 1.1.0.15.jar) Unloaded->Constructed
	tropicraftmod{v5.1.7 for MC 1.6.4} [Tropicraft] (Tropicraft v5.1.7 Mod for MC v1.6.4.jar) Unloaded->Constructed
	volleyballmod{v5.1.7 for MC 1.6.4} [Volleyball] (Tropicraft v5.1.7 Mod for MC v1.6.4.jar) Unloaded->Constructed
	AIBlock{v1.0} [AIBlock] (Weather v1.591 Mod for MC v1.6.4.zip) Unloaded->Constructed
	WeatherMod{1.591} [Weather and Tornadoes] (Weather v1.591 Mod for MC v1.6.4.zip) Unloaded->Constructed
	WebDisplay{0.7} [Web Displays] (WebDisplays-0.7.zip) Unloaded->Constructed
	mod_ZanMinimap{0.9.4} [Zan's Minimap] (ZansMinimap1.6.4.zip) Unloaded->Constructed
	McMultipart{1.0.0.244} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed
	ForgeMicroblock{1.0.0.244} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed
	TConstruct Environment: Sane and ready for action. Bugs may be reported.

**Comment by 4f6f3b** [comment]
You can paste logs at http://pastebin.com/ and just share the pastebin url, it keeps things less cluttered here. :)

As far as this log goes, you can't delete files from inside jars otherwise you will guarantee to crash. Please add a fresh Fossils jar and if it errors again give me the new log.

**Comment by Ssherlockhemlock** [comment]
That is a new one, i've redownloaded it a few times to see if it worked but nothing changed

**Comment by 4f6f3b** [comment]
Oh I see the issue now. Build 7.x only works with Minecraft 1.7, while Build 7.1 is only for Minecraft 1.7.10. We haven't supported 1.6.4 in a while, and we just dropped 1.7.2 because of time and resources.

**Comment by Ssherlockhemlock** [comment]
So what do i need to do then, I really want this mod to work.

**Comment by 4f6f3b** [comment]
If you are dead set with having to use 1.6.4, this: http://www.mediafire.com/download/x07rhmywdlcx8zy/Fossils_Archeology_Revival-1.6.4_Build-6.4.1.jar is the final 1.6.4 version. Note that it's missing quite a few things and features from the most up to date version.

Otherwise you'll have to update to Minecraft 1.7.10.

**Comment by Ssherlockhemlock** [comment]
I thought i had updated minecraft because i redownloaded when the problem started to see if that was the issue. I've redownloaded it again now but it still says 1.6.4

**Comment by Ssherlockhemlock** [comment]
I've opened up vanilla minecraft where it says its 1.8.3, but when i open the technic launcher, where I've added your mod to a pack it says 1.6.4 and still crashes.

**Comment by 4f6f3b** [comment]
What are you using for your Minecraft launcher?

**Comment by Ssherlockhemlock** [comment]
What do you mean? For vanilla I'm going into my applications and starting it from there, for the technic launcher I'm using its .jar file.
