### ISSUE TITLE
Deinonychus use the same sounds as Dilophosaurus.

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilArcheology1.7#108]
And since there's now a sound guy, they should both make unique noises.

**Comment by 4f6f3b** [comment]
Technically Nano does music, and not sound fx. :)

**Comment by Adsper** [comment]
Oh... That's less of an issue. But still.

**Comment by PCAwesomeness** [comment]
Not anymore!

Close this, please.

**Comment by PCAwesomeness** [comment]
When will this be closed?
