### ISSUE TITLE
Red ceratosaurus has something wrong with the end of it's tail.

### ISSUE THREAD

**Issue by SirMuffinz** [FossilsArcheologyRevival/FossilArcheology1.7#124]
I came across this when I was walking past it.
![2015-06-07_16 17 25](https://cloud.githubusercontent.com/assets/8330592/8025816/212d20d0-0d31-11e5-8f82-3dc0fc2c0141.png)

**Comment by SirMuffinz** [comment]
It may be kind of hard to see, it's a little sliver by the end.

**Comment by Bluestreak52** [comment]
Trust me, this is an issue that I am completely aware about, and I intend for it to get fixed in the next update.

**Comment by SirMuffinz** [comment]
Thanks =D. Keep up the good work as always!

**Comment by 4f6f3b** [comment]
Fixed as of 7.2.1
