### ISSUE TITLE
Problem with Confucisornis...

### ISSUE THREAD

**Issue by ethanwait25** [FossilsArcheologyRevival/FossilArcheology1.7#130]
There's a major problem (not a glitch or bug) with the Confucisornis. Since it had such a large upper arm bone, expert paleontologists say it could not flap upwards. It couldn't move its wings above a horizontal position. In the mod, it flaps up and down, it needs to stop at the horizontal position and go back down. Sorry, it's just bugging me.

**Comment by PCAwesomeness** [comment]
You know, Pteranodon had such big wings, they'd have to soar all the time. Yet the one in the mod flaps its wings.

So, I dunno if they'd like to fix both or not.

**Comment by ethanwait25** [comment]
It would be more accurate. :P lol

**Comment by PCAwesomeness** [comment]
Perhaps.
