### ISSUE TITLE
I don't want to be that guy, but...

### ISSUE THREAD

**Issue by ethanwait25** [FossilsArcheologyRevival/FossilArcheology1.7#133]
I don't want to be that guy, but this mod needs more herbivorous mammals. It would be awesome if someone made a Paraceratherium. Thanks! (Remember, I've never suggested anything before, so don't kill me...)

**Comment by Bluestreak52** [comment]
We have quite a few herbivorous mammals, such as the Mammoth and the Elasmotherium, as the Smilodon is the only carnivorous mammal we have.

**Comment by PCAwesomeness** [comment]
As Blue said, Smilodon is the only carnivorous mammal...

Also, IMO, mammals are not the problem here. They are extremely lacking in Paleozoic creatures. (This is not a suggestion)

**Comment by lalaladinosaur** [comment]
I don't think we have ANY Paleozoic creatures... I think we need at least one dinosaur from each group. (Therapod, Sorapod, Ceratopcian, ECT) Mind my spelling
