### ISSUE TITLE
Baby T-Rex Missing Texture

### ISSUE THREAD

**Issue by RobertoM99** [FossilsArcheologyRevival/FossilArcheology1.7#138]
You may have already seen this on your twitter, but the baby Tyrannosaurs are missing their textures. The adults seem to keep their textures
![2015-06-07_15 22 58](https://cloud.githubusercontent.com/assets/12833289/8088520/8fbd7f4e-0f67-11e5-95bf-6725c150f6c9.png)

**Comment by FearTheswoop** [comment]
I also had this same issue.

**Comment by 4f6f3b** [comment]
Fixed as of 7.2.1
