### ISSUE TITLE
Dupe Bug with Analyser

### ISSUE THREAD

**Issue by Kehaan** [FossilsArcheologyRevival/FossilArcheology1.7#139]
Hello

I have seen another also reported a dupe bug. But this was not with the analyser.

I have made a gif of it here: http://gyazo.com/3979fefb0810329789e9c5ce27497fc6

Open the Analyser, and shift click any item. The item you shift click will get doubled.

Using newest version of the mod :)

- Kehaan

**Comment by 4f6f3b** [comment]
Fixed as of 7.2.1

**Comment by lalaladinosaur** [comment]
NOOOOO IT'S FIXED! I SHOULD HAVE KNOWN EARLIER!
