### ISSUE TITLE
Palaeoraphe leaves despawning

### ISSUE THREAD

**Issue by FearTheswoop** [FossilsArcheologyRevival/FossilArcheology1.7#144]
Leaf blocks on a palaeoraphe tree immediately start despawning when the tree grows.  It seems as though the palaeoraphe trunk blocks aren't recognized as wood, causing the leaves to despawn.

**Comment by LiteraryRecluse** [comment]
I have the same issue.

**Comment by LiteraryRecluse** [comment]
I just placed them in creative mode as hedges and they started to despawn that way as well.
