### ISSUE TITLE
Baby Feathered T-Rex Still Missing Texture

### ISSUE THREAD

**Issue by RobertoM99** [FossilsArcheologyRevival/FossilArcheology1.7#149]
The baby feathered Tyrannosaurs still do not have their textures. The un-feathered babys have their texture, but the feathered ones don't
![2015-06-14_22 53 30](https://cloud.githubusercontent.com/assets/12833289/8152873/826b4e6e-12e8-11e5-89b9-56457d7da61d.png)

**Comment by lalaladinosaur** [comment]
So creepy!

**Comment by RobertoM99** [comment]
The baby feathered T-Rex seems to not have textures until it reaches day 5 of age. Then it's textures appear.

**Comment by AglarCZ** [comment]
Any progress on this? Wil it be repaired soon?
