### ISSUE TITLE
Iron Golems still dicks to Plesio and Mosa skeletons for some reason.

### ISSUE THREAD

**Issue by Bluestreak52** [FossilsArcheologyRevival/FossilArcheology1.7#15]

**Comment by koppisme** [comment]
make a room to prevent that. plus the skeleton is just the same as bones but it cant move ore be moved or die in the sun.

**Comment by darthvader45** [comment]
Maybe make it so dino skeletons are classified as a passive entity, since they're just bones, and not supposed to move.

**Comment by koppisme** [comment]
they did. if u have the damage indicators mod u see that they have health un like bloks I think it you should have to use there  bones in the crafting table to get there skeleton.

**Comment by darthvader45** [comment]
I know, but since iron golems are attacking them, they seem to be classed as hostile mobs.

**Comment by koppisme** [comment]
ahh I see

**Comment by 4f6f3b** [comment]
The way java works and the way the skeletons are set up (frozen skinned mobs) there's little you can do about that. We have plans on reworking on how you get and build skeletons but there's nothing much to say about it at this point.

**Comment by darthvader45** [comment]
Ok, thanks for clearing that up.  Maybe have them as TileEntities?

On Mon, Apr 13, 2015 at 2:24 PM, 4f6f3b <notifications@github.com> wrote:

> The way java works and the way the skeletons are set up (frozen skinned
> mobs) there's little you can do about that. We have plans on reworking on
> how you get and build skeletons but there's nothing much to say about it at
> this point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FossilsArcheologyRevival/FossilArcheology1.7/issues/15#issuecomment-92451745>
> .
>



-- 
Golden rule in Minecraft: Never dig straight down.

**Comment by Alex-the-666** [comment]
Fixed and in next update.
