### ISSUE TITLE
Fossil Blocks only give Triceratops related bones.

### ISSUE THREAD

**Issue by Dynotank** [FossilsArcheologyRevival/FossilArcheology1.7#156]
When mined the Fossil Blocks give the usual bio-fossils, relic scraps, ect. When it gives animal fossils the only animal that can be found is Triceratops. For example the only type of skulls that can be found are Triceratops.

**Comment by 4f6f3b** [comment]
What mod version are you using?

**Comment by Dynotank** [comment]
The newest version 7.2.1

**Comment by Dynotank** [comment]
Sorry I forgot to mention that it also happens when a Brachiosaurus breaks the fossil blocks.

**Comment by 4f6f3b** [comment]
Very strange, I just tested it right now and the dinosaur bones are dropping as they should.

**Comment by Dynotank** [comment]
Weird must be something on my end. It didn't always do that, only after 7.2
