### ISSUE TITLE
Umm... Is this supposed to happen?

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilArcheology1.7#158]
This happened when Anu got into his obsidian box... 
![2015-06-23_21 33 47](https://cloud.githubusercontent.com/assets/11862143/8322787/aa0533dc-19ef-11e5-92d9-48e10418c7a2.png)

**Comment by 4f6f3b** [comment]
Haha. I've never seen that happen before. That would be terrible if Anu escaped through it.
