### ISSUE TITLE
Missing T-rex texture

### ISSUE THREAD

**Issue by MoonLitGaming** [FossilsArcheologyRevival/FossilArcheology1.7#159]
I haev tried everything from removing my texture pack or replaceing the mods. Non of that works. 
![2015-06-24_12 37 27](https://cloud.githubusercontent.com/assets/13038741/8339651/e805a3be-1a6d-11e5-88cc-1b7660b4ad24.png)

**Comment by iLexiconn** [comment]
https://github.com/FossilsArcheologyRevival/FossilArcheology1.7/issues/149
