### ISSUE TITLE
Screen goes... black?

### ISSUE THREAD

**Issue by NemesisKismet** [FossilsArcheologyRevival/FossilArcheology1.7#162]
Whenever I get a game alert like "A dinosaur has hatched!" the top half of my screen goes black and I can't see anything. The bottom half goes white except for a strip where the alert text sits and where my item bar is...
![bug](https://cloud.githubusercontent.com/assets/13070402/8387825/5dc89b6a-1c21-11e5-8e06-7404d421c5eb.png)

**Comment by 4f6f3b** [comment]
This seems to be an issue with the helmet overlays.

For now you can disable the overlays by changing

    B:Skull_Overlay=

to false in the config.
