### ISSUE TITLE
Analyzer Craft Recipe Issue

### ISSUE THREAD

**Issue by kc83** [FossilsArcheologyRevival/FossilArcheology1.7#163]
![2015-06-27_11 34 55](https://cloud.githubusercontent.com/assets/13078546/8392808/0b739654-1cc5-11e5-967a-a17e604dcf3b.png)

I've been having this issue, I just installed the mod last night. The mod itself works, I've found plenty of fossils and new creatures and even a sunken ship, but for whatever reason I can not craft the analyzer even though I'm using the right recipe. I've re-installed the mod a few times, looked up the issue itself on your forums, but now I'd rather just ask for help. I'm sure it's something simple on my end.

Using Minecraft version 1.7.10, latest mod update, and Forge 10.13.4.1448 - 1.7.10

**Comment by 4f6f3b** [comment]
Are you using other mods?

This might also be a metadata issue with the dropped bio-fossil or relic scrap. Try hitting "F3+H", and this will allow you to see item ID + metadata and make sure there is no metadata on the fossils/relic scraps.

**Comment by kc83** [comment]
This is actually the first mod I have tried, ever, in Minecraft lol. 

The item IDs on both of those items are what they should be, I'm not seeing any metadata information after the ID.

**Comment by 4f6f3b** [comment]
Hmmm That's really strange. And this will do it in any world you create?

**Comment by kc83** [comment]
lol, I just tried it in another world and I can craft it. I was so attached to the one world I never bothered trying in another. I kinda like the new one anyway. Hopefully it was just some odd isolated thing.

**Comment by Glitchyminecraft** [comment]
maybe the iron ingots are having metadata. or download personalized recipes mod and make your own recipe for it. or try moving the crafting recipe a row up.
