### ISSUE TITLE
Allosaurus gets stuck in terrain

### ISSUE THREAD

**Issue by Croak90** [FossilsArcheologyRevival/FossilArcheology1.7#169]
My fully grown Allosaurus suddenly stopped moving at the edge of a small pond only 1 water block deep. I noticed he was tracking nearby sheep with his head and when pushed close to him he'd kill them and eat them without moving from the spot. I could not push him nor hit him from the spot. After digging out the blocks under him he fell below the surface and proceeded to suffocate and die in a wall.

**Comment by Alex-the-666** [comment]
7.3 will fix
