### ISSUE TITLE
Culture vat issues

### ISSUE THREAD

**Issue by jennielouwho92** [FossilsArcheologyRevival/FossilArcheology1.7#176]
On placing any item in the vat it will not return anything. For example I placed DNA and a bucket of milk. It did not return an empty bucket but the milk loaded into the vat and the vat proceeded to work. It did not indicate a failure so when opening the vat nothing was present. No DNA, no egg, no bucket.

**Comment by Glitchyminecraft** [comment]
another issue, when a culture vat generates a failure plant, you wont get the seeds back and also no iron ingots. and if there is a block 1 block higher than directly on top of the culture vat, the block will dissappear and not dropand the failure plant will drop as a resource.
