### ISSUE TITLE
Config button wont work 

### ISSUE THREAD

**Issue by Demytrix** [FossilsArcheologyRevival/FossilArcheology1.7#180]
![bandicam 2015-07-10 17-33-16-814](https://cloud.githubusercontent.com/assets/13271650/8615993/2bf4ed50-272a-11e5-9341-f1562fbf877d.jpg)
The config button wont work
I cant change the t-rex and velociraptor to unfeathered

**Comment by 4f6f3b** [comment]
For now, you can still go into your /config folder, open up the fossil.cfg file and change the scales config to true, like so.

```
    B:"Tyrannosaurus Scales"=true
    B:"Velociraptor Scales"=true
```

**Comment by Demytrix** [comment]
Where can I find config folder?
in .minecraft?

**Comment by Demytrix** [comment]
NVM
I already figured it out
I found it and used notepad to edit
Tnx
