### ISSUE TITLE
Deinonychus Jumping In Place

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilArcheology1.7#181]
This happens frequently when a Deinonychus tries to climb a block and just starts jumping up and down instead of going forward. The only way to get them out of this is to push them. As far as I know this doesn't happen with any of the other dinosaurs.
![2015-07-11_22 50 39](https://cloud.githubusercontent.com/assets/11862143/8636594/91f340fc-281f-11e5-9c78-72225d9206c7.png)

**Comment by PCAwesomeness** [comment]
This happens to any mob.

Close this, please.

**Comment by Adsper** [comment]
I know, but with the other mobs it's just a minor thing that they do every so often when they're idling which they eventually break out of. The Deino's do this half of the time they try to climb a block and they don't fix themselves, even if they need food (you can see a feeder that this Deino was heading for in the pic).

**Comment by iLexiconn** [comment]
This is a vanilla bug
