### ISSUE TITLE
Dino's not breeding...

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilArcheology1.7#183]
So I've had a large fenced in area with about 10 Deinonychus that mostly hang out in the back. I've spend about 7+ hours in all in this world, and not once have I seen a baby Deino or a Deino egg. I've double checked to make sure breeding is on, and I've made sure that nothing can obstruct an egg, but still nothing. I also have exhibits with Sarcosuchus, Plesiosaurs and Pachycephalosaurs that have had no babies. I think breeding is bugged. Halp.

**Comment by lalaladinosaur** [comment]
Is it on the official server? If so, breeding is ioff

**Comment by Adsper** [comment]
It's on single player.
