### ISSUE TITLE
Dupe bug with the analyzer

### ISSUE THREAD

**Issue by timmay237** [FossilsArcheologyRevival/FossilArcheology1.7#186]
If you shift click items in the analyzer it doubles the stack.

**Comment by 4f6f3b** [comment]
What mod version?

**Comment by mich4075** [comment]
it is mod version this : FOSSILS_ARCHEOLOGY_REVIVAL-1.7.10_BUILD-7.2

**Comment by 4f6f3b** [comment]
Update to build 7.2.1, the issue was fixed in that version.
