### ISSUE TITLE
Incompatible with Agricraft

### ISSUE THREAD

**Issue by belleindigo** [FossilsArcheologyRevival/FossilArcheology1.7#196]
Hello!

After lots of troubleshooting, I've discovered that the latest version of Fossils and Archeology Revival and Agricraft version 1.3.1 crash upon being loaded by Forge Modloader (version 10.13.4.1492).

**Comment by 4f6f3b** [comment]
Is there a crash log?

**Comment by iLexiconn** [comment]
(side note: always use the recommended version! the test versions are for... testing)

**Comment by airbreather** [comment]
I'm guessing this is the same issue we just ran into today.  Fossils and Archeology Revival [hardcodes 10](https://github.com/FossilsArcheologyRevival/FossilArcheology1.7/blob/089ed815e12ed338863444f93e6fbe9bbbaa0873/src/main/java/com/github/revival/Revival.java#L116-L117) as its [new villager](https://github.com/MinecraftForge/FML/blob/c3912836dcb0961a3d77a24253ab2fa97188c1af/src/main/java/cpw/mods/fml/common/registry/VillagerRegistry.java#L116-L128) profession [ID](https://github.com/MinecraftForge/FML/blob/c3912836dcb0961a3d77a24253ab2fa97188c1af/src/main/java/cpw/mods/fml/common/registry/VillagerRegistry.java#L155-L164).  Agricraft's new villager profession ID defaults to 10, but Agricraft's config file lets you override it.

Changing the ID in Agricraft's config from 10 to something else fixed this for us.

Note that this appears to [no longer be an issue](https://github.com/InfinityRaider/AgriCraft/commit/7ff6d72e43f71856edad74de12cf804331948b25) in versions of AgriCraft 1.4.0 and above, though those are still marked as "beta" for now.
