### ISSUE TITLE
update release date

### ISSUE THREAD

**Issue by AglarCZ** [FossilsArcheologyRevival/FossilArcheology1.7#199]
Hello,
as owner of F/A server i am very interested in next update for 1.7.10. 

As i read on reddit, there should be one major update for this version before moving to 1.8 right?
Is this update coming soon (= in august) or will it take more time?

I am going to make major update of the server modpack so it quite depends of F/A update as long as we are not using technic autoupdate but our own launcher.

**Comment by AglarCZ** [comment]
Any response please?

**Comment by 4f6f3b** [comment]
No ETA on the next update. It's not much to go off of, but I think we're past 50% complete.

As the update gets closer to being finished we'll be announcing more things more frequently; follow @FossilsRevival on Twitter to stay up to date.

If you have any specific concerns about F/A updates for your server, feel free to contact me directly, either through the Minecraft Forums, or you can email fossils.revival -at- gmail.com

**Comment by AglarCZ** [comment]
Ok, thanks for info.
