### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by MythixDino** [FossilsArcheologyRevival/FossilArcheology1.7#201]
There's a duplication bug with the analyser that isn't fixed yet, when you shift+click an item the amount will be doubled.

This should been have fixed, but there's no way to download the new version (7.2.1).

**Comment by ilethalize** [comment]
Yes, can you please have a look at it since people on our server keep on abusing it.

**Comment by 4f6f3b** [comment]
What version of the mod are you using? As far as we know it was fixed in 7.2.1, and I've had no reports of it on my own server.

**Comment by MythixDino** [comment]
I'm using 7.2, because there was no way to download the new version. Now it's fixed.

**Comment by 4f6f3b** [comment]
Sorry about that, I didn't find out until last night that the download link on the forum page was changed to an outdated build.

**Comment by Sunconure11** [comment]
Can we re-open this? I just encountered this with the analyzer.

**Comment by Sunconure11** [comment]
NVM, the version on curse is outdated.
