### ISSUE TITLE
conflict mod

### ISSUE THREAD

**Issue by 4f6f3b** [FossilsArcheologyRevival/FossilArcheology1.7#202]
SvEgiiVEteR commented from https://github.com/FossilsArcheologyRevival/FossilArcheology1.6/issues/387
> PneumaticCraft 123
> MineMaarten/PneumaticCraft#673
> 121 ок

**Comment by MineMaarten** [comment]
Figured it out, it turns out Fossils and Archeology registers null item(stack)s to the villager registry. Added defence on my end, but fyi.
