### ISSUE TITLE
tps loss cause of mobs

### ISSUE THREAD

**Issue by VanironCZ** [FossilsArcheologyRevival/FossilArcheology1.7#204]
Hi,
on my server (latest cauldron) i found bug, when any F/A mob is bugged into wall (just fence around his area) and then start lagging the server as shown on this tickprofiler report: http://prntscr.com/8j6cpm

The mob is not in whole wall, just touching the block or so..

Is there any option how to prevent this tps loss?

**Comment by Alex-the-666** [comment]
oh, it seems to be ticking to check if it can be breaking blocks, however if this feature is turned off it might continuously tick. I'll definitely go and check it out.

**Comment by AglarCZ** [comment]
Great, i would be really happy if we can find solution together :)

**Comment by 4f6f3b** [comment]
Do you have block breaking on or off? 

Maybe using https://github.com/sk89q/WarmRoast could help pinpoint what the cause is..

**Comment by AglarCZ** [comment]
Block breaking is on. I cant use WarmRoast cause being on hosted server = only access to ftp and server console.

**Comment by 4f6f3b** [comment]
Oh, I see you're using cauldron. If you use Worldguard, you can type

>  /wg profile -p

And worldguard will profile your server for 5 minutes then give you a link to view the results.

**Comment by AglarCZ** [comment]
Server is okay now (as most of the time) but here is the log: http://dinocraft.cz/profile.txt

**Comment by AglarCZ** [comment]
Any news?

**Comment by 4f6f3b** [comment]
We're aware of some performance issues, at least with the eating AI. I've resorted to turning off block breaking as well as dinosaur starvation on my server until we have a solution for it. I know it's not ideal turning those off, but on average I've gained 5-6 TPS from that.

**Comment by AglarCZ** [comment]
Ok i will try that too. Thanks of info.

**Comment by 4f6f3b** [comment]
Let me know how that works out for you.

**Comment by AglarCZ** [comment]
Still tps loss. Any other idea? Eta on mod update?

**Comment by VanironCZ** [comment]
Any idea?

**Comment by 4f6f3b** [comment]
Disabling block breaking, dinosaur breeding, and dinosaur hunger should make F/A run light. Otherwise you'll have to look at your other mods and plugins to figure out what you could optimize there.
