### ISSUE TITLE
Coal not stacking

### ISSUE THREAD

**Issue by zenieldanaku** [FossilsArcheologyRevival/FossilArcheology1.7#206]
Whenever an Analyzed fossil returns coal (which happens quite often), that piece of coal does not stacks with normal coal. I found that the returned coal has a different block ID. Is it possible to make the coal the analyzer returns be normal, stacking coal?

**Comment by 4f6f3b** [comment]
What mod version?

**Comment by zenieldanaku** [comment]
the mod version is 7.2.1 (the latest, according to the wiki page). I have found that the returned coal has a data value of 2, that it should be 0 (1 is for charcoal). That small change should be sufficient to solve this issue, I think.

**Comment by zenieldanaku** [comment]
Cool, I just have one more question left regarding this: is the build released yet? I ask because I do not see it.

**Comment by iLexiconn** [comment]
Nope, the fix isn't released yet.

**Comment by zenieldanaku** [comment]
Ok, then I'll wait for it. Thanks!

**Comment by ethanwait25** [comment]
I'm asking this question because his question is similar to mine. I've always wondered. There's a download button on the main GitHub page. If I downloaded it, would I be able to play this latest mod version?

**Comment by zenieldanaku** [comment]
@ethanwait25 This is not the better place to answer that question, but if you go to the main page (following the link "FossilArcheology1.7") and you click on the "releases" tab, you will see a green button on your left. That's the lastest release. However, the wiki page has the same release (build) as the lastest. There it seems to be no "release candidate" or "beta" versions per se.

**Comment by iLexiconn** [comment]
Sorry for my late reply, but you can download the compiled version of the latest source code [here](http://ci.ilexiconn.net/job/Fossils%20and%20Archeology%20Revival%207.x/) (they're very unstable, though!)

**Comment by zenieldanaku** [comment]
Late? IMHO yours is a very fast reply!

**Comment by ethanwait25** [comment]
Thanks lexiconn
