### ISSUE TITLE
Interaction with Buldcraft's Pipes

### ISSUE THREAD

**Issue by zenieldanaku** [FossilsArcheologyRevival/FossilArcheology1.7#207]
In my opinion, it would be nice if milk could be piped to a culture vat, instead of (or in addition to) inserted with a bucket. This would require a change in the GUI (maybe a gauge like Railcraft's iron tanks, or Buldcraft's engines), and maybe a tweak with Ore Dictionary or something like that. This would improve automatization.

**Comment by Alex-the-666** [comment]
Please post suggestions in the FA wiki forum instead. http://fossils-archeology.wikia.com/wiki/Board:Suggestions
