### ISSUE TITLE
Mosasaurus and Liopleurodon don't suffocate when on land.

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilArcheology1.7#212]

**Comment by apotheoseGrifter** [comment]
Mosasaurs and plesiosaurs (Liopleurodon is a type of plesiosaur) were air-breathers; they wouldn't suffocate outside of water. They might be crushed by their own weight if they're large enough, like beached whales do, but that seems like an unnecessary complication.

**Comment by Alex-the-666** [comment]
"

Mosasaurs and plesiosaurs (Liopleurodon is a type of plesiosaur) were air-breathers; they wouldn't suffocate outside of water. They might be crushed by their own weight if they're large enough, like some beached whales, but that seems like an unnecessary complication."

^^^^^^^

**Comment by ethanwait25** [comment]
I agree with ads per about it being annoying... But maybe you should make it just like a beached whale...it can't get more than ten or so blocks away from the water. Because it is very annoying when they escape.

**Comment by ethanwait25** [comment]
And really unrealistic! Do you think they roamed around like amphibians? So... Maybe in the future you could do that
