### ISSUE TITLE
Ender IO Conflict

### ISSUE THREAD

**Issue by cortus** [FossilsArcheologyRevival/FossilArcheology1.7#216]
Build 7.2.1
  It seems that while using the dinopedia while wearing dark leggings from Ender IO, but only with the speed upgrades, that it totally crashes the client.  There is no crash while wearing dark leggings without the speed upgrades.  Tested with potions of swiftness alone and no crash.
[crash-2015-11-21_08.19.34-client.txt](https://github.com/FossilsArcheologyRevival/FossilArcheology1.7/files/40843/crash-2015-11-21_08.19.34-client.txt)

**Comment by mizziness** [comment]
Build 7.2.1
I, too, am having a crash like this one, but I am not running Ender IO.  I am, though, wearing armor with speed upgrades from Artifacts.  I use the DinoPedia and the client instantly crashes.
[crash-2015-12-14_15.56.01-client.txt](https://github.com/FossilsArcheologyRevival/FossilArcheology1.7/files/61754/crash-2015-12-14_15.56.01-client.txt)

**Comment by Alex-the-666** [comment]
Interesting, I'll probably remove the nonsensical Container from the gui and make it completely client side, and hope it works.

**Comment by iLexiconn** [comment]
Any updates on this?
