### ISSUE TITLE
Minetweaker support

### ISSUE THREAD

**Issue by Sunconure11** [FossilsArcheologyRevival/FossilArcheology1.7#218]
Just what it says on the tin. Minetweaker should be supported, so that one can create new recipes using the various new devices and such in this mod.

**Comment by Alex-the-666** [comment]
Does Minetweaker have an api? I've never really used it :B

**Comment by Sunconure11** [comment]
https://github.com/stanhebben/MineTweaker3/tree/master/MineTweaker3-API

**Comment by Alex-the-666** [comment]
Please move your suggestion to the FA Suggestion forums: http://fossils-archeology.wikia.com/wiki/Board:Suggestions
