### ISSUE TITLE
Issue with Thaumcraft

### ISSUE THREAD

**Issue by LoLMist3rEvil** [FossilsArcheologyRevival/FossilArcheology1.7#228]
Thaumcraft 4.2.3.5 and Fossils 2.7.1 aren't working together. Here is the crash report. :)
[crash-2016-01-25_23.51.52-client.txt](https://github.com/FossilsArcheologyRevival/FossilArcheology1.7/files/104124/crash-2016-01-25_23.51.52-client.txt)

**Comment by Alex-the-666** [comment]
Change either Thaumcraft Villager ID's or Fossils Villager ID's.
