### ISSUE TITLE
Mobs attack from very far away.

### ISSUE THREAD

**Issue by Alex-the-666** [FossilsArcheologyRevival/FossilArcheology1.7#237]
This is caused by the dinosaur needing to attack in onLivingUpdate(), as in this EntityTyrannosaurus.class.
```
 public void onLivingUpdate(){
    	super.onLivingUpdate();
    	if(this.getAnimation() == this.animation_attack && this.getAnimationTick() == 12 && this.getAttackTarget() != null){
    		this.attackEntityAsMob(this.getAttackTarget());
    	}
    }
```

We need to put a distance check in here, I'm not sure how but I think Gegy would know.

**Comment by gegy1000** [comment]
Fixed this using boundingBox.intersects(entity.boundingBox)
