### ISSUE TITLE
Dinosaurus fall very weirdly.

### ISSUE THREAD

**Issue by Alex-the-666** [FossilsArcheologyRevival/FossilArcheology1.7#238]
Place a dino on top of a nerd-pole and push it off. it glitches off and acts weird. I assume this has to do with the leftover climbing code.

**Comment by Alex-the-666** [comment]
Trying to assign both @gegy1000  and @iLexiconn  :P

**Comment by gegy1000** [comment]
Do you mean jittery falling? If not, I can't seem to reproduce this.

**Comment by Alex-the-666** [comment]
yeah i meant jittery falling.

**Comment by gegy1000** [comment]
Hmm, okay.

**Comment by iLexiconn** [comment]
It's a feature
