### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by iLexiconn** [FossilsArcheologyRevival/FossilArcheology1.7#244]
https://pastebin.com/raw/Fi3UENLw

**Comment by Alex-the-666** [comment]
"[18:56:33] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/client/model/tools/ChainBuffer"

**Comment by iLexiconn** [comment]
Not a proper fix
