### ISSUE TITLE
Misspell 

### ISSUE THREAD

**Issue by ethanwait25** [FossilsArcheologyRevival/FossilArcheology1.7#253]
This is the latest issue ever, but... 
Someone on the forums posted a picture of a pteranodon with the new Dino pediatric. Just thought I'd bring it to your attention that "activity=diurinal" should be "activity=diurnal". Simple misspell. Fixed I  three seconds. It's just diurinal isn't a word, but diurnal means like the opposite of nocturnal. I think that's what you meant because you recently added nocturnal ai.

**Comment by ethanwait25** [comment]
Oh and BTW... Not the latest issue ever. The LAMEST issue ever.

**Comment by Sunconure11** [comment]
https://github.com/FossilsArcheologyRevival/FossilArcheology1.7/pull/254

This pull should fix it, I'm waiting for someone to merge it.
