### ISSUE TITLE
Animal Belly Size Suggestions

### ISSUE THREAD

**Issue by Bluestreak52** [FossilsArcheologyRevival/FossilArcheology1.7#256]
Tyrannosaurus - 150
Triceratops - 175
Velociraptor - 75
Pteranodon - 100
Nautilus - 25
Mosasaurus - 125
Plesiosaurus - 100
Mammoth - 150
Smilodon - 100
Dilophosaurus - 100
Stegosaurus - 175
Brachiosaurus - 250
Spinosaurus - 175
Compsognathus - 50
Dodo - 50
Ankylosaurus - 175
Pachycephalosaurus - 100
Deinonychus - 100
Gallimimus - 100
Liopleurodon - 125
Quagga - 100
Elasmotherium - 125
Allosaurus - 125
Terror Birds - 75
Sarcosuchus - 150
Confuciusornis - 25
Ceratosaurus - 100

**Comment by PCAwesomeness** [comment]
Why is the Nautilus on there?
