### ISSUE TITLE
I really have no idea what to make of this.

### ISSUE THREAD

**Issue by ClockworkGod** [FossilsArcheologyRevival/FossilArcheology1.7#58]
Game Version 1.7.10 and forge 1230.

I play with this mod in a custom mod pack, if I have this mod installed, sometimes I run into an issue where when I break blocks, nothing drops, sand/gravel doesn't fall, water/lava doesn't flow and I am unable to interact with any tile entities. The game also hangs when I try to save and quit.T his is in a single player world, so its not a server sync issue, and the console doesn't have any thrown errors or anything, no crash log is reported. 

Edit: forgot to mention, the issue starts when i enter certain chunks, though I have no idea what is exactly special about these chunks.

**Comment by koppisme** [comment]
use forge  1236 it works like a boss
