### ISSUE TITLE
Sifter animation keeps playing bug.

### ISSUE THREAD

**Issue by raptorfarian** [FossilsArcheologyRevival/FossilArcheology1.7#59]
When you use the sifter in the latest version of the mod the animation keeps playing even after sifting is complete and when you break the block it is named after the animation block and not called a sifter.

**Comment by lalaladinosaur** [comment]
yes, it says tile.sifter.name something P.S. Raptor when i reported the bug to u, u just took my sifter

**Comment by lalaladinosaur** [comment]
SO GIVE IT BACK
