### ISSUE TITLE
A few bugs with the current version.

### ISSUE THREAD

**Issue by JTGhawk137** [FossilsArcheologyRevival/FossilArcheology1.7#69]
First of all, the brachiosaurus needs to be properly positioned. Second of all, the sarcosuchus moves when it is weak and in the weak model (Which should not happen), it also needs to switch to the weak texture. The pterosaur also has a texture problem when switching from the flying to ground. also the sarcosuchus legs have a texture glitch (ask raptor about it)

**Comment by Alex-the-666** [comment]
fixed in v. 7.1.
