### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by dy126800** [FossilsArcheologyRevival/FossilArcheology1.7#73]
Altough It was great, I spotted few errors and problems in the new korean translation, and I think I could make a improved translation for the mod. Is there any way to contribute?

**Comment by 4f6f3b** [comment]
Hey dy, if you'd still like to contribute you can visit this spreadsheet. 

https://docs.google.com/spreadsheets/d/12T5tH3G-CvwwPDi20MZdn_I2dNz5ILMlZl4Igvx1Kmo/edit#gid=0

Scroll all the way to the right and there should be a column for the Korean translation. If you make changes please let me know. :)

**Comment by dy126800** [comment]
Thank you, 4f! I'll leave a comment here if I make any changes.

**Comment by dy126800** [comment]
Made a lot of changes today, especially with dinosaur/item names.

**Comment by lalaladinosaur** [comment]
can i help translate too?

**Comment by lalaladinosaur** [comment]
im helping :)

**Comment by lalaladinosaur** [comment]
4f3f4b did u use goofle translate?  Cuz some of them were way off
