### ISSUE TITLE
Help! Tamed Dinosaurs keep breeding untamed offspring

### ISSUE THREAD

**Issue by wildsharks** [FossilsArcheologyRevival/FossilArcheology1.7#84]
My tamed Dinosaurs keep breeding untamed offspring. In the Wiki, it said that tamed/owned dinosaurs will produce tamed offspring but not sure why it doesn't. Even some videos that I watched had their offspring tamed from tamed parents.

**Comment by 4f6f3b** [comment]
Naturally spawned eggs and hand placed eggs all use the same taming mechanic, so in either case you have to be within that certain distance for the baby to become tamed. Eggs dropped by dinosaurs are not automatically tamed and that has always been the case. :)
