### ISSUE TITLE
Worldgen spawn dimension

### ISSUE THREAD

**Issue by CaptainSisko** [FossilsArcheologyRevival/FossilArcheology1.7#85]
Not a bug, the wiki said that this is also a place for suggestions.

Would it be possible to add an option to the config that would allow you to set which dimensions the worldgen (fossils, permafrost) spawns in?

This would allow people who use mods like "Aroma1997s Dimensional World" to make it so the worldgen spawns there.

**Comment by 4f6f3b** [comment]
We'll look into and see if it's possible to add such a config.
