### ISSUE TITLE
Bones record doesn't work

### ISSUE THREAD

**Issue by smallpred** [FossilsArcheologyRevival/FossilArcheology1.7#89]
I have It playing but I hear nothing :/

**Comment by 4f6f3b** [comment]
It works on my end, so this may be difficult to figure out. What launcher are you using to run Minecraft with? Is it the vanilla launcher?

**Comment by smallpred** [comment]
technic launcher and vanilla I tried it on both but I can hear nuthin :/

**Comment by 4f6f3b** [comment]
Can you verify the other music discs work in a jukebox?

**Comment by smallpred** [comment]
all discs work except for the bones one :/

**Comment by 4f6f3b** [comment]
Closing, myself and others that I've had tested have not had this issue.
