### ISSUE TITLE
Baby Pteranodon constantly giving message "no room to grow"

### ISSUE THREAD

**Issue by SquatchyLP** [FossilsArcheologyRevival/FossilArcheology1.7#97]
My two nether-variant Pteranodons will not grow past baby stage. I am constantly seeing the message "Pteranodon has no room to grow". I have put them on a completely flat space and tried leaving them at all three command stages (follow, stay, etc.) and still I get nothing.

**Comment by 4f6f3b** [comment]
a12b89f49712937039c8e9d8f3a831b8190e1760
