### ISSUE TITLE
Some Sarco Problems

### ISSUE THREAD

**Issue by Adsper** [FossilsArcheologyRevival/FossilArcheology1.7#98]
First, they won't eat any farm animals, fish, Nautilus, Coelacanth or pretty much any mob. 

Second, their hit box is EXTREMELY off. You can push them from 3 blocks away, and they will stop in front of blocks when it clearly looks like they can keep going. They will often float off blocks when it looks like they should be falling.

Third, I don't know if this ties in with the hitbox issue, but you can hit them through one block thick walls sometimes.

And fourth: Baby Sarco's will often swim in one spot without moving, for a long period of time (for example, they will only move a few blocks every 30 seconds or so). I don't know if this continues into adulthood or if it also applies to land.

Edit: Also I forgot a minor one: Sarco spawn eggs are in the wrong place in the creative tabs, they should be at the end of the spawn egg list but they're in front of the Triceratops spawn egg (which is the first one) instead.

**Comment by 4f6f3b** [comment]
These issues are noted, but for future reference make sure to open up a separate ticket for every issue instead of listening them all in one. It makes it easier to fix and check them off by themselves.

**Comment by Adsper** [comment]
Will do.
