### ISSUE TITLE
Corrupted recipes

### ISSUE THREAD

**Issue by MC-Soupcup** [FossilsArcheologyRevival/FossilArcheology1.7#99]
So I have FAR version 7.1 in a modpack and recieved an error from Hardcore Ender Expansion, the following lines are from the forge log, the crash report just says it found corrupt recipes and purposefully crashed.

    Corrupted shaped recipe: <null> <= {<null>, <null>, <empty>, <null>, <null>, <empty>,<empty>, <empty>, <empty>}
    Corrupted shaped recipe: <null> <= {<empty>, <null>, <null>, <empty>, <null>, <null>,<empty>, <empty>, <empty>}
    Corrupted shaped recipe: <null> <= {<empty>, <empty>, <empty>, <empty>, <null>, <null>, <empty>, <null>, <null>}
    Corrupted shaped recipe: <null> <= {<empty>, <empty>, <empty>, <empty>, <null>, <null>, <empty>, <null>, <null>}

HEE now does this thing where it'll crash the game when it detects a corrupted recipe (unless you have a config option on that disables corrupt recipes it finds). I've found that disabling your mod stops this crash from happening, which in turn tells me that the recipes are from FAR. It doesn't really say what recipes they are, but I figured posting the four there seem to be here might help, plus it shows which spots where items are supposed to be, marked null, might help it be tracked down.

The recipes look almost like stone-brick type recipes (2x2 pattern of a block), not sure what that would tell you though. In-game, with HEE disabled so recipes aren't disabled, I've noticed that ancient stone brick isn't craftable, might be that? Anyways, I just thought I'd put this here, and if you need any more info, let me know. Thank you!

**Comment by 4f6f3b** [comment]
Thank you for the detailed bug report! I looked and it looks like the culprits are the limestone brick recipes, though I am not able to test right now. If those are the problem, this will be resolved in the next update.

**Comment by MC-Soupcup** [comment]
For now they're fine, that HEE config option just disables, as you said, the limestone brick recipes. I'm just glad it's not disabling more major recipes. It disables things because the recipes can corrupt worlds if you try to craft them when they're corrupted, or something along those lines. Anyways, thank you for the quick response!

**Comment by Alex-the-666** [comment]
Solved!
